#!/usr/bin/python

import os
import sys
import spadic

#--------------------------------------------------------------------
# parse options
#--------------------------------------------------------------------
reset = "--reset" in sys.argv
full_error = "--full-error" in sys.argv

try:
    log_file = sys.argv[sys.argv.index("--log")+1]
except:
    log_file = "/tmp/spadic/spadic.log"
log_dir = os.path.dirname(os.path.abspath(log_file))
if not os.path.exists(log_dir):
    os.makedirs(log_dir)
log_file_p = open(log_file, 'w')

try:
    load_file = sys.argv[sys.argv.index("--load")+1]
except:
    load_file = None

#--------------------------------------------------------------------
# start spadic controller and user interface
#--------------------------------------------------------------------
try:
    with spadic.Spadic(reset=reset, load=load_file,
                       _debug_cbmif=1, _debug_out=log_file_p) as s:
        s.ui_run()
except:
    if full_error:
        raise
    else:
        sys.exit(sys.exc_value)

