#!/usr/bin/python

import os
import socket
import sys

from spadic.client import SpadicControlClient

#--------------------------------------------------------------------
# parse options
#--------------------------------------------------------------------
reset = "--reset" in sys.argv
full_error = "--full-error" in sys.argv

try:
    log_file = sys.argv[sys.argv.index("--log")+1]
except:
    log_file = "/tmp/spadic/spadic.log"
log_dir = os.path.dirname(os.path.abspath(log_file))
if not os.path.exists(log_dir):
    os.makedirs(log_dir)
log_file_p = open(log_file, 'w')

try:
    load_file = sys.argv[sys.argv.index("--load")+1]
except:
    load_file = None

try:
    hostname = sys.argv[sys.argv.index("--host")+1]
except:
    hostname = socket.gethostname()

#--------------------------------------------------------------------
# start spadic controller and user interface
#--------------------------------------------------------------------
try:
    with SpadicControlClient(hostname, reset=reset, load=load_file) as c:
        c.ui_run()
except:
    if full_error:
        raise
    else:
        sys.exit(sys.exc_value)

