#!/usr/bin/env python

import sys

from spadic.tools import SpadicDataMonitor, SpadicScope 


host = sys.argv[sys.argv.index('--host')+1]
try:
    ch = int(sys.argv[sys.argv.index('--ch')+1])
except ValueError:
    ch = 31

with SpadicDataMonitor(host) as mon:
    scope = SpadicScope(mon, channel=ch)
    scope.run()

