#!/usr/bin/python

import os
import sys
import time

try:
    from spadic import SpadicServer
except ImportError:
    raise SystemExit("Could not import SpadicServer. "
                     "Do you have libFTDI installed properly?")

#--------------------------------------------------------------------
# parse options
#--------------------------------------------------------------------
reset = "--reset" in sys.argv
full_error = "--full-error" in sys.argv

try:
    log_file = sys.argv[sys.argv.index("--log")+1]
    log_dir = os.path.dirname(os.path.abspath(log_file))
    if not os.path.exists(log_dir):
        os.makedirs(log_dir)
    log_file_p = open(log_file, 'w')
except:
    log_file_p = None

try:
    _debug = int(sys.argv[sys.argv.index("--debug")+1], 0)
except:
    _debug = 0b110 # default: server+cbmif
_debug_ftdi   = (_debug>>0) & 1
_debug_cbmif  = (_debug>>1) & 1
_debug_server = (_debug>>2) & 1

try:
    load_file = sys.argv[sys.argv.index("--load")+1]
except:
    load_file = None

try:
    port = int(sys.argv[sys.argv.index("--port")+1])
except:
    port = None

#--------------------------------------------------------------------
# start spadic server
#--------------------------------------------------------------------
options = {'reset':         reset,
           'load':          load_file,
           'port_base':     port,
           '_debug_ftdi':   _debug_ftdi,
           '_debug_cbmif':  _debug_cbmif,
           '_debug_server': _debug_server,
           '_debug_out':    log_file_p}

try:
    with SpadicServer(**options) as s:
        while True:
            try:
                time.sleep(1)
            except KeyboardInterrupt:
                break
except:
    if full_error:
        raise
    else:
        sys.exit(sys.exc_value)

