#!/usr/bin/python3

import os
import logging
import sys
import time

try:
    from spadic import SpadicServer
except ImportError:
    raise SystemExit("Could not import SpadicServer. "
                     "Do you have libFTDI installed properly?")

#--------------------------------------------------------------------
# parse options
#--------------------------------------------------------------------
reset = "--reset" in sys.argv
full_error = "--full-error" in sys.argv

try:
    log_level = sys.argv[sys.argv.index("--log")+1]
except:
    log_level = "warning"
logging.basicConfig(level=getattr(logging, log_level.upper()))

try:
    load_file = sys.argv[sys.argv.index("--load")+1]
except:
    load_file = None

try:
    port = int(sys.argv[sys.argv.index("--port")+1])
except:
    port = None

#--------------------------------------------------------------------
# start spadic server
#--------------------------------------------------------------------
options = {'reset':         reset,
           'load':          load_file,
           'port_base':     port}

try:
    with SpadicServer(**options) as s:
        while True:
            try:
                time.sleep(1)
            except KeyboardInterrupt:
                break
except:
    if full_error:
        raise
    else:
        sys.exit(sys.exc_info()[1])

