# ex: syntax=python

libmessage = SharedLibrary(['message.c'])
libtestmessage = SharedLibrary(['test_message.c', libmessage])

cpp_env = Environment(CCFLAGS=['-std=c++11'])
cpp_env.Program(['test_message.cpp', libtestmessage, libmessage])
