# ex: syntax=python

env = Environment(LIB_DIR='../../', CPPPATH=['../../'])
env_cpp = env.Clone(CCFLAGS=['--std=c++11'])

libmessage = env.SharedLibrary('$LIB_DIR/message.c')
libmessage_cpp = env_cpp.SharedLibrary(['Message.cpp', libmessage])
