# ex: syntax=python

env = Environment(LIB_DIR='../../', CPPPATH=['../../'])
env_cpp = env.Clone(CCFLAGS=['--std=c++11'])

libmessage = env.SharedLibrary('$LIB_DIR/message.c')
libreader = env.SharedLibrary(['$LIB_DIR/message_reader.c', libmessage])

libmessage_cpp = env_cpp.SharedLibrary(['Message.cpp', libmessage, libreader])

prog = env_cpp.Program('test', ['test.cpp', libmessage_cpp, libmessage])
